### ISSUE TITLE
bug(cli): `devaudit update` crashes with `cmd.optsWithGlobals is not a function` (regression in 0.1.56)

### ISSUE THREAD

**Issue by ostendo-io** [metasession-dev/DevAudit-Installer#162]
### What
`npx @metasession.co/devaudit-cli@latest update` (0.1.56 / 0.1.57) crashes immediately:

```
TypeError: cmd.optsWithGlobals is not a function
    at Command.<anonymous> (.../dist/index.js:2911:25)
```

### Root cause
Regression from the #154 dry-run wiring. commander invokes an action with `(…declared-args, options, command)`. `update [version] [paths...]` has **two** declared args, so the `Command` is the **fourth** parameter — but the handler was `(version, paths, cmd)`, binding `cmd` to the **third** param (the options object), which has no `optsWithGlobals()`.

### Why tests missed it
The `update` unit tests call `runUpdate()` directly and never exercise commander's action arg-binding. No test drove the actual CLI for `update`.

### Fix
- Correct the action parameter list (`(version, paths, _options, cmd)`).
- Add a regression test that runs the **built binary** (`update --dry-run <fixture>`) through commander.

Affects all consumers on 0.1.56 / 0.1.57. Patched in 0.1.58.
